// Code generated by Microsoft Kiota - DO NOT EDIT.

use std::collections::HashMap;
use kiota_abstractions::{KiotaError, Parsable, ParseNode, SerializationWriter};

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Error {
    /// The error documentation URL
    pub documentation_url: Option<String>,
    /// The error message
    pub message: Option<String>,
    pub additional_data: HashMap<String, serde_json::Value>,
}

impl Parsable for Error {
    fn field_names(&self) -> Vec<&'static str> {
        vec!["documentation_url", "message"]
    }

    fn assign_field(&mut self, field: &str, node: &dyn ParseNode) -> Result<(), KiotaError> {
        match field {
            "documentation_url" => self.documentation_url = node.get_string_value()?,
            "message" => self.message = node.get_string_value()?,
            _ => {}
        }
        Ok(())
    }

    fn serialize(&self, writer: &mut dyn SerializationWriter) -> Result<(), KiotaError> {
        if let Some(ref val) = self.documentation_url { writer.write_string_value(Some("documentation_url"), val)?; }
        if let Some(ref val) = self.message { writer.write_string_value(Some("message"), val)?; }
        writer.write_additional_data(&self.additional_data)?;
        Ok(())
    }

    fn as_any(self: Box<Self>) -> Box<dyn std::any::Any> {
        self
    }
}

impl Error {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn create_from_discriminator_value(_parse_node: &dyn ParseNode) -> Result<Self, KiotaError> {
        Ok(Self::default())
    }
    pub fn get_additional_data(&self) -> &HashMap<String, serde_json::Value> {
        &self.additional_data
    }
    pub fn get_documentation_url(&self) -> &Option<String> {
        &self.documentation_url
    }
    pub fn get_message(&self) -> &Option<String> {
        &self.message
    }
    pub fn set_additional_data(&mut self, value: HashMap<String, serde_json::Value>) {
        self.additional_data = value;
    }
    pub fn set_documentation_url(&mut self, value: Option<String>) {
        self.documentation_url = value;
    }
    pub fn set_message(&mut self, value: Option<String>) {
        self.message = value;
    }
}
