// Code generated by Microsoft Kiota - DO NOT EDIT.

use std::collections::HashMap;
use kiota_abstractions::{KiotaError, Parsable, ParseNode, SerializationWriter};
use chrono;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Release {
    /// The release body
    pub body: Option<String>,
    /// The release creation date
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The release ID
    pub id: Option<i32>,
    /// The release name
    pub name: Option<String>,
    /// The release publication date
    pub published_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The release tag name
    pub tag_name: Option<String>,
    pub additional_data: HashMap<String, serde_json::Value>,
}

impl Parsable for Release {
    fn field_names(&self) -> Vec<&'static str> {
        vec!["body", "created_at", "id", "name", "published_at", "tag_name"]
    }

    fn assign_field(&mut self, field: &str, node: &dyn ParseNode) -> Result<(), KiotaError> {
        match field {
            "body" => self.body = node.get_string_value()?,
            "created_at" => self.created_at = node.get_date_time_value()?,
            "id" => self.id = node.get_i32_value()?,
            "name" => self.name = node.get_string_value()?,
            "published_at" => self.published_at = node.get_date_time_value()?,
            "tag_name" => self.tag_name = node.get_string_value()?,
            _ => {}
        }
        Ok(())
    }

    fn serialize(&self, writer: &mut dyn SerializationWriter) -> Result<(), KiotaError> {
        if let Some(ref val) = self.body { writer.write_string_value(Some("body"), val)?; }
        if let Some(ref val) = self.created_at { writer.write_date_time_value(Some("created_at"), val)?; }
        if let Some(val) = self.id { writer.write_i32_value(Some("id"), val)?; }
        if let Some(ref val) = self.name { writer.write_string_value(Some("name"), val)?; }
        if let Some(ref val) = self.published_at { writer.write_date_time_value(Some("published_at"), val)?; }
        if let Some(ref val) = self.tag_name { writer.write_string_value(Some("tag_name"), val)?; }
        writer.write_additional_data(&self.additional_data)?;
        Ok(())
    }

    fn as_any(self: Box<Self>) -> Box<dyn std::any::Any> {
        self
    }
}

impl Release {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn create_from_discriminator_value(_parse_node: &dyn ParseNode) -> Result<Self, KiotaError> {
        Ok(Self::default())
    }
    pub fn get_additional_data(&self) -> &HashMap<String, serde_json::Value> {
        &self.additional_data
    }
    pub fn get_body(&self) -> &Option<String> {
        &self.body
    }
    pub fn get_created_at(&self) -> &Option<chrono::DateTime<chrono::FixedOffset>> {
        &self.created_at
    }
    pub fn get_id(&self) -> &Option<i32> {
        &self.id
    }
    pub fn get_name(&self) -> &Option<String> {
        &self.name
    }
    pub fn get_published_at(&self) -> &Option<chrono::DateTime<chrono::FixedOffset>> {
        &self.published_at
    }
    pub fn get_tag_name(&self) -> &Option<String> {
        &self.tag_name
    }
    pub fn set_additional_data(&mut self, value: HashMap<String, serde_json::Value>) {
        self.additional_data = value;
    }
    pub fn set_body(&mut self, value: Option<String>) {
        self.body = value;
    }
    pub fn set_created_at(&mut self, value: Option<chrono::DateTime<chrono::FixedOffset>>) {
        self.created_at = value;
    }
    pub fn set_id(&mut self, value: Option<i32>) {
        self.id = value;
    }
    pub fn set_name(&mut self, value: Option<String>) {
        self.name = value;
    }
    pub fn set_published_at(&mut self, value: Option<chrono::DateTime<chrono::FixedOffset>>) {
        self.published_at = value;
    }
    pub fn set_tag_name(&mut self, value: Option<String>) {
        self.tag_name = value;
    }
}
