// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, RequestAdapter};
use crate::repos::repos_request_builder::ReposRequestBuilder;

/// The main entry point of the SDK, exposes the configuration and the fluent API.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct GitHubReleasesClient {
    pub base: BaseRequestBuilder,
}

impl GitHubReleasesClient {
    /// The repos property
    pub fn repos(&self) -> ReposRequestBuilder {
        ReposRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    pub fn new(request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        if request_adapter.base_url().is_empty() {
            path_parameters.insert("baseurl".to_string(), "https://api.github.com".to_string());
        } else {
            path_parameters.insert("baseurl".to_string(), request_adapter.base_url().to_string());
        }
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}".to_string(), path_parameters),
        }
    }
}
