// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, DefaultQueryParameters, HttpMethod, KiotaError, Parsable, ParseNode, RequestAdapter, RequestConfiguration, RequestInformation};
use crate::models::user::User;
use crate::user::create_with_array::create_with_array_request_builder::CreateWithArrayRequestBuilder;
use crate::user::create_with_list::create_with_list_request_builder::CreateWithListRequestBuilder;
use crate::user::item::with_username_item_request_builder::WithUsernameItemRequestBuilder;
use crate::user::login::login_request_builder::LoginRequestBuilder;
use crate::user::logout::logout_request_builder::LogoutRequestBuilder;

/// Builds and executes requests for operations under \user
#[derive(Debug, Clone, Default, PartialEq)]
pub struct UserRequestBuilder {
    pub base: BaseRequestBuilder,
}

impl UserRequestBuilder {
    /// The createWithArray property
    pub fn create_with_array(&self) -> CreateWithArrayRequestBuilder {
        CreateWithArrayRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    /// The createWithList property
    pub fn create_with_list(&self) -> CreateWithListRequestBuilder {
        CreateWithListRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    /// The login property
    pub fn login(&self) -> LoginRequestBuilder {
        LoginRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    /// The logout property
    pub fn logout(&self) -> LogoutRequestBuilder {
        LogoutRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    /// Gets an item from the petstore_client.user.item collection
    pub fn by_username(&self, username: String) -> WithUsernameItemRequestBuilder {
        let mut url_tpl_params = self.base.path_parameters.clone();
        url_tpl_params.insert("username".to_string(), username.to_string());
        WithUsernameItemRequestBuilder::new(url_tpl_params, self.base.request_adapter.clone())
    }
    pub fn new(path_parameters: std::collections::HashMap<String, String>, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}/user".to_string(), path_parameters),
        }
    }
    pub fn with_url(raw_url: &str, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        path_parameters.insert("request-raw-url".to_string(), raw_url.to_string());
        Self {
            base: BaseRequestBuilder::new(request_adapter, String::new(), path_parameters),
        }
    }
    /// This can only be done by the logged in user.
    pub async fn post(&self, body: &Option<User>, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<Option<Vec<u8>>, KiotaError> {
        let request_info = self.to_post_request_information(body, config)?;
        self.base.request_adapter.send_primitive(&request_info, None).await
    }
    /// This can only be done by the logged in user.
    pub fn to_post_request_information(&self, body: &Option<User>, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Post, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        if let Some(ref b) = body {
            request_info.set_content_from_parsable(self.base.request_adapter.serialization_writer_factory(), "application/json", b as &dyn Parsable)?;
        }
        Ok(request_info)
    }
}
