// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, RequestAdapter};
use crate::repos::item::item::with_repo_item_request_builder::WithRepoItemRequestBuilder;

/// Builds and executes requests for operations under \repos\{owner}
#[derive(Debug, Clone, Default, PartialEq)]
pub struct WithOwnerItemRequestBuilder {
    pub base: BaseRequestBuilder,
}

impl WithOwnerItemRequestBuilder {
    /// Gets an item from the github_releases_client.repos.item.item collection
    pub fn by_repo(&self, repo: String) -> WithRepoItemRequestBuilder {
        let mut url_tpl_params = self.base.path_parameters.clone();
        url_tpl_params.insert("repo".to_string(), repo.to_string());
        WithRepoItemRequestBuilder::new(url_tpl_params, self.base.request_adapter.clone())
    }
    pub fn new(path_parameters: std::collections::HashMap<String, String>, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}/repos/{owner}".to_string(), path_parameters),
        }
    }
    pub fn with_url(raw_url: &str, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        path_parameters.insert("request-raw-url".to_string(), raw_url.to_string());
        Self {
            base: BaseRequestBuilder::new(request_adapter, String::new(), path_parameters),
        }
    }
}
