// Code generated by Microsoft Kiota - DO NOT EDIT.

use std::collections::HashMap;
use kiota_abstractions::{KiotaError, Parsable, ParseNode, SerializationWriter};

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WithPetPostRequestBody {
    /// Updated name of the pet
    pub name: Option<String>,
    /// Updated status of the pet
    pub status: Option<String>,
    pub additional_data: HashMap<String, serde_json::Value>,
}

impl Parsable for WithPetPostRequestBody {
    fn field_names(&self) -> Vec<&'static str> {
        vec!["name", "status"]
    }

    fn assign_field(&mut self, field: &str, node: &dyn ParseNode) -> Result<(), KiotaError> {
        match field {
            "name" => self.name = node.get_string_value()?,
            "status" => self.status = node.get_string_value()?,
            _ => {}
        }
        Ok(())
    }

    fn serialize(&self, writer: &mut dyn SerializationWriter) -> Result<(), KiotaError> {
        if let Some(ref val) = self.name { writer.write_string_value(Some("name"), val)?; }
        if let Some(ref val) = self.status { writer.write_string_value(Some("status"), val)?; }
        writer.write_additional_data(&self.additional_data)?;
        Ok(())
    }

    fn as_any(self: Box<Self>) -> Box<dyn std::any::Any> {
        self
    }
}

impl WithPetPostRequestBody {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn create_from_discriminator_value(_parse_node: &dyn ParseNode) -> Result<Self, KiotaError> {
        Ok(Self::default())
    }
    pub fn get_additional_data(&self) -> &HashMap<String, serde_json::Value> {
        &self.additional_data
    }
    pub fn get_name(&self) -> &Option<String> {
        &self.name
    }
    pub fn get_status(&self) -> &Option<String> {
        &self.status
    }
    pub fn set_additional_data(&mut self, value: HashMap<String, serde_json::Value>) {
        self.additional_data = value;
    }
    pub fn set_name(&mut self, value: Option<String>) {
        self.name = value;
    }
    pub fn set_status(&mut self, value: Option<String>) {
        self.status = value;
    }
}
