// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, DefaultQueryParameters, HttpMethod, KiotaError, Parsable, ParseNode, RequestAdapter, RequestConfiguration, RequestInformation};
use crate::models::order::Order;

/// Builds and executes requests for operations under \store\order\{orderId}
#[derive(Debug, Clone, Default, PartialEq)]
pub struct WithOrderItemRequestBuilder {
    pub base: BaseRequestBuilder,
}

impl WithOrderItemRequestBuilder {
    pub fn new(path_parameters: std::collections::HashMap<String, String>, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}/store/order/{orderId}".to_string(), path_parameters),
        }
    }
    pub fn with_url(raw_url: &str, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        path_parameters.insert("request-raw-url".to_string(), raw_url.to_string());
        Self {
            base: BaseRequestBuilder::new(request_adapter, String::new(), path_parameters),
        }
    }
    /// For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
    pub async fn delete(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<Option<Vec<u8>>, KiotaError> {
        let request_info = self.to_delete_request_information(config)?;
        self.base.request_adapter.send_primitive(&request_info, None).await
    }
    /// For valid response try integer IDs with value &gt;= 1 and &lt;= 10. Other values will generated exceptions
    pub async fn get(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<Option<Order>, KiotaError> {
        let request_info = self.to_get_request_information(config)?;
        let factory: Box<dyn Fn(&dyn ParseNode) -> Result<Box<dyn Parsable>, KiotaError> + Send + Sync> =
            Box::new(|node| Ok(Box::new(Order::create_from_discriminator_value(node)?)));
        let result = self.base.request_adapter.send(&request_info, &factory, None).await?;
        Ok(result.and_then(|r| r.as_any().downcast::<Order>().ok().map(|b| *b)))
    }
    /// For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
    pub fn to_delete_request_information(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Delete, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        Ok(request_info)
    }
    /// For valid response try integer IDs with value &gt;= 1 and &lt;= 10. Other values will generated exceptions
    pub fn to_get_request_information(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Get, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        Ok(request_info)
    }
}
