// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, RequestAdapter};
use crate::posts::posts_request_builder::PostsRequestBuilder;

/// The main entry point of the SDK, exposes the configuration and the fluent API.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct PostsClient {
    pub base: BaseRequestBuilder,
}

impl PostsClient {
    /// The posts property
    pub fn posts(&self) -> PostsRequestBuilder {
        PostsRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    pub fn new(request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        if request_adapter.base_url().is_empty() {
            path_parameters.insert("baseurl".to_string(), "https://jsonplaceholder.typicode.com".to_string());
        } else {
            path_parameters.insert("baseurl".to_string(), request_adapter.base_url().to_string());
        }
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}".to_string(), path_parameters),
        }
    }
}
