// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, DefaultQueryParameters, HttpMethod, KiotaError, MultipartBody, Parsable, ParseNode, RequestAdapter, RequestConfiguration, RequestInformation};
use crate::models::api_response::ApiResponse;

/// Builds and executes requests for operations under \pet\{petId}\uploadImage
#[derive(Debug, Clone, Default, PartialEq)]
pub struct UploadImageRequestBuilder {
    pub base: BaseRequestBuilder,
}

impl UploadImageRequestBuilder {
    pub fn new(path_parameters: std::collections::HashMap<String, String>, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}/pet/{petId}/uploadImage".to_string(), path_parameters),
        }
    }
    pub fn with_url(raw_url: &str, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        path_parameters.insert("request-raw-url".to_string(), raw_url.to_string());
        Self {
            base: BaseRequestBuilder::new(request_adapter, String::new(), path_parameters),
        }
    }
    /// uploads an image
    pub async fn post(&self, body: &Option<MultipartBody>, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<Option<ApiResponse>, KiotaError> {
        let request_info = self.to_post_request_information(body, config)?;
        let factory: Box<dyn Fn(&dyn ParseNode) -> Result<Box<dyn Parsable>, KiotaError> + Send + Sync> =
            Box::new(|node| Ok(Box::new(ApiResponse::create_from_discriminator_value(node)?)));
        let result = self.base.request_adapter.send(&request_info, &factory, None).await?;
        Ok(result.and_then(|r| r.as_any().downcast::<ApiResponse>().ok().map(|b| *b)))
    }
    pub fn to_post_request_information(&self, body: &Option<MultipartBody>, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Post, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        if let Some(ref b) = body {
            request_info.set_content_from_parsable(self.base.request_adapter.serialization_writer_factory(), "multipart/form-data", b as &dyn Parsable)?;
        }
        Ok(request_info)
    }
}
