// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, RequestAdapter};
use crate::pet::pet_request_builder::PetRequestBuilder;
use crate::store::store_request_builder::StoreRequestBuilder;
use crate::user::user_request_builder::UserRequestBuilder;

/// The main entry point of the SDK, exposes the configuration and the fluent API.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct PetstoreClient {
    pub base: BaseRequestBuilder,
}

impl PetstoreClient {
    /// The pet property
    pub fn pet(&self) -> PetRequestBuilder {
        PetRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    /// The store property
    pub fn store(&self) -> StoreRequestBuilder {
        StoreRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    /// The user property
    pub fn user(&self) -> UserRequestBuilder {
        UserRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    pub fn new(request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        if request_adapter.base_url().is_empty() {
            path_parameters.insert("baseurl".to_string(), "https://petstore.swagger.io/v2".to_string());
        } else {
            path_parameters.insert("baseurl".to_string(), request_adapter.base_url().to_string());
        }
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}".to_string(), path_parameters),
        }
    }
}
