// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, DefaultQueryParameters, HttpMethod, KiotaError, Parsable, ParseNode, RequestAdapter, RequestConfiguration, RequestInformation};

/// Builds and executes requests for operations under \user\login
#[derive(Debug, Clone, Default, PartialEq)]
pub struct LoginRequestBuilder {
    pub base: BaseRequestBuilder,
}

impl LoginRequestBuilder {
    pub fn new(path_parameters: std::collections::HashMap<String, String>, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}/user/login?password={password}&username={username}".to_string(), path_parameters),
        }
    }
    pub fn with_url(raw_url: &str, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        path_parameters.insert("request-raw-url".to_string(), raw_url.to_string());
        Self {
            base: BaseRequestBuilder::new(request_adapter, String::new(), path_parameters),
        }
    }
    /// Logs user into the system
    pub async fn get(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<Option<String>, KiotaError> {
        let request_info = self.to_get_request_information(config)?;
        todo!("unknown return type")
    }
    pub fn to_get_request_information(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Get, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        Ok(request_info)
    }
}
