// Code generated by Microsoft Kiota - DO NOT EDIT.

use std::collections::HashMap;
use kiota_abstractions::{KiotaError, Parsable, ParseNode, SerializationWriter};

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ApiResponse {
    /// The code property
    pub code: Option<i32>,
    /// The message property
    pub message: Option<String>,
    /// The type property
    pub r#type: Option<String>,
    pub additional_data: HashMap<String, serde_json::Value>,
}

impl Parsable for ApiResponse {
    fn field_names(&self) -> Vec<&'static str> {
        vec!["code", "message", "type"]
    }

    fn assign_field(&mut self, field: &str, node: &dyn ParseNode) -> Result<(), KiotaError> {
        match field {
            "code" => self.code = node.get_i32_value()?,
            "message" => self.message = node.get_string_value()?,
            "type" => self.r#type = node.get_string_value()?,
            _ => {}
        }
        Ok(())
    }

    fn serialize(&self, writer: &mut dyn SerializationWriter) -> Result<(), KiotaError> {
        if let Some(val) = self.code { writer.write_i32_value(Some("code"), val)?; }
        if let Some(ref val) = self.message { writer.write_string_value(Some("message"), val)?; }
        if let Some(ref val) = self.r#type { writer.write_string_value(Some("type"), val)?; }
        writer.write_additional_data(&self.additional_data)?;
        Ok(())
    }

    fn as_any(self: Box<Self>) -> Box<dyn std::any::Any> {
        self
    }
}

impl ApiResponse {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn create_from_discriminator_value(_parse_node: &dyn ParseNode) -> Result<Self, KiotaError> {
        Ok(Self::default())
    }
    pub fn get_additional_data(&self) -> &HashMap<String, serde_json::Value> {
        &self.additional_data
    }
    pub fn get_code(&self) -> &Option<i32> {
        &self.code
    }
    pub fn get_message(&self) -> &Option<String> {
        &self.message
    }
    pub fn get_type(&self) -> &Option<String> {
        &self.r#type
    }
    pub fn set_additional_data(&mut self, value: HashMap<String, serde_json::Value>) {
        self.additional_data = value;
    }
    pub fn set_code(&mut self, value: Option<i32>) {
        self.code = value;
    }
    pub fn set_message(&mut self, value: Option<String>) {
        self.message = value;
    }
    pub fn set_type(&mut self, value: Option<String>) {
        self.r#type = value;
    }
}
