// Code generated by Microsoft Kiota - DO NOT EDIT.

use std::collections::HashMap;
use kiota_abstractions::{KiotaError, Parsable, ParseNode, SerializationWriter};
use chrono;
use crate::models::order_status::OrderStatus;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Order {
    /// The complete property
    pub complete: Option<bool>,
    /// The id property
    pub id: Option<i64>,
    /// The petId property
    pub pet_id: Option<i64>,
    /// The quantity property
    pub quantity: Option<i32>,
    /// The shipDate property
    pub ship_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Order Status
    pub status: Option<OrderStatus>,
    pub additional_data: HashMap<String, serde_json::Value>,
}

impl Parsable for Order {
    fn field_names(&self) -> Vec<&'static str> {
        vec!["complete", "id", "petId", "quantity", "shipDate", "status"]
    }

    fn assign_field(&mut self, field: &str, node: &dyn ParseNode) -> Result<(), KiotaError> {
        match field {
            "complete" => self.complete = node.get_bool_value()?,
            "id" => self.id = node.get_i64_value()?,
            "petId" => self.pet_id = node.get_i64_value()?,
            "quantity" => self.quantity = node.get_i32_value()?,
            "shipDate" => self.ship_date = node.get_date_time_value()?,
            "status" => self.status = node.get_string_value()?.and_then(|s| OrderStatus::parse(&s)),
            _ => {}
        }
        Ok(())
    }

    fn serialize(&self, writer: &mut dyn SerializationWriter) -> Result<(), KiotaError> {
        if let Some(val) = self.complete { writer.write_bool_value(Some("complete"), val)?; }
        if let Some(val) = self.id { writer.write_i64_value(Some("id"), val)?; }
        if let Some(val) = self.pet_id { writer.write_i64_value(Some("petId"), val)?; }
        if let Some(val) = self.quantity { writer.write_i32_value(Some("quantity"), val)?; }
        if let Some(ref val) = self.ship_date { writer.write_date_time_value(Some("shipDate"), val)?; }
        if let Some(ref val) = self.status { writer.write_string_value(Some("status"), &val.to_string())?; }
        writer.write_additional_data(&self.additional_data)?;
        Ok(())
    }

    fn as_any(self: Box<Self>) -> Box<dyn std::any::Any> {
        self
    }
}

impl Order {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn create_from_discriminator_value(_parse_node: &dyn ParseNode) -> Result<Self, KiotaError> {
        Ok(Self::default())
    }
    pub fn get_additional_data(&self) -> &HashMap<String, serde_json::Value> {
        &self.additional_data
    }
    pub fn get_complete(&self) -> &Option<bool> {
        &self.complete
    }
    pub fn get_id(&self) -> &Option<i64> {
        &self.id
    }
    pub fn get_pet_id(&self) -> &Option<i64> {
        &self.pet_id
    }
    pub fn get_quantity(&self) -> &Option<i32> {
        &self.quantity
    }
    pub fn get_ship_date(&self) -> &Option<chrono::DateTime<chrono::FixedOffset>> {
        &self.ship_date
    }
    pub fn get_status(&self) -> &Option<OrderStatus> {
        &self.status
    }
    pub fn set_additional_data(&mut self, value: HashMap<String, serde_json::Value>) {
        self.additional_data = value;
    }
    pub fn set_complete(&mut self, value: Option<bool>) {
        self.complete = value;
    }
    pub fn set_id(&mut self, value: Option<i64>) {
        self.id = value;
    }
    pub fn set_pet_id(&mut self, value: Option<i64>) {
        self.pet_id = value;
    }
    pub fn set_quantity(&mut self, value: Option<i32>) {
        self.quantity = value;
    }
    pub fn set_ship_date(&mut self, value: Option<chrono::DateTime<chrono::FixedOffset>>) {
        self.ship_date = value;
    }
    pub fn set_status(&mut self, value: Option<OrderStatus>) {
        self.status = value;
    }
}
