// Code generated by Microsoft Kiota - DO NOT EDIT.

/// Order Status
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OrderStatus {
    Placed,
    Approved,
    Delivered,
}

impl std::fmt::Display for OrderStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Placed => write!(f, "placed"),
            Self::Approved => write!(f, "approved"),
            Self::Delivered => write!(f, "delivered"),
        }
    }
}

impl OrderStatus {
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "placed" => Some(Self::Placed),
            "approved" => Some(Self::Approved),
            "delivered" => Some(Self::Delivered),
            _ => None,
        }
    }
}
