// Code generated by Microsoft Kiota - DO NOT EDIT.

use std::collections::HashMap;
use kiota_abstractions::{KiotaError, Parsable, ParseNode, SerializationWriter};
use crate::models::category::Category;
use crate::models::pet_status::PetStatus;
use crate::models::tag::Tag;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Pet {
    /// The category property
    pub category: Option<Category>,
    /// The id property
    pub id: Option<i64>,
    /// The name property
    pub name: Option<String>,
    /// The photoUrls property
    pub photo_urls: Vec<String>,
    /// pet status in the store
    pub status: Option<PetStatus>,
    /// The tags property
    pub tags: Vec<Tag>,
    pub additional_data: HashMap<String, serde_json::Value>,
}

impl Parsable for Pet {
    fn field_names(&self) -> Vec<&'static str> {
        vec!["category", "id", "name", "photoUrls", "status", "tags"]
    }

    fn assign_field(&mut self, field: &str, node: &dyn ParseNode) -> Result<(), KiotaError> {
        match field {
            "category" => {
                let mut obj = Category::default();
                for f in obj.field_names().to_vec() {
                    if let Ok(Some(n)) = node.get_child_node(f) { obj.assign_field(f, n.as_ref())?; }
                }
                self.category = Some(obj);
            }
            "id" => self.id = node.get_i64_value()?,
            "name" => self.name = node.get_string_value()?,
            "photoUrls" => self.photo_urls = node.get_collection_of_string_values()?,
            "status" => self.status = node.get_string_value()?.and_then(|s| PetStatus::parse(&s)),
            "tags" => {
                let mut items = Vec::new();
                for child in node.get_child_nodes()? {
                    let mut obj = Tag::default();
                    for f in obj.field_names().to_vec() {
                        if let Ok(Some(n)) = child.get_child_node(f) { obj.assign_field(f, n.as_ref())?; }
                    }
                    items.push(obj);
                }
                self.tags = items;
            }
            _ => {}
        }
        Ok(())
    }

    fn serialize(&self, writer: &mut dyn SerializationWriter) -> Result<(), KiotaError> {
        if let Some(ref val) = self.category { writer.write_object_value(Some("category"), val as &dyn Parsable, &[])?; }
        if let Some(val) = self.id { writer.write_i64_value(Some("id"), val)?; }
        if let Some(ref val) = self.name { writer.write_string_value(Some("name"), val)?; }
        writer.write_collection_of_string_values(Some("photoUrls"), &self.photo_urls.iter().map(|v| v.to_string()).collect::<Vec<_>>())?;
        if let Some(ref val) = self.status { writer.write_string_value(Some("status"), &val.to_string())?; }
        // TODO: serialize collection of objects for tags
        writer.write_additional_data(&self.additional_data)?;
        Ok(())
    }

    fn as_any(self: Box<Self>) -> Box<dyn std::any::Any> {
        self
    }
}

impl Pet {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn create_from_discriminator_value(_parse_node: &dyn ParseNode) -> Result<Self, KiotaError> {
        Ok(Self::default())
    }
    pub fn get_additional_data(&self) -> &HashMap<String, serde_json::Value> {
        &self.additional_data
    }
    pub fn get_category(&self) -> &Option<Category> {
        &self.category
    }
    pub fn get_id(&self) -> &Option<i64> {
        &self.id
    }
    pub fn get_name(&self) -> &Option<String> {
        &self.name
    }
    pub fn get_photo_urls(&self) -> &Vec<String> {
        &self.photo_urls
    }
    pub fn get_status(&self) -> &Option<PetStatus> {
        &self.status
    }
    pub fn get_tags(&self) -> &Vec<Tag> {
        &self.tags
    }
    pub fn set_additional_data(&mut self, value: HashMap<String, serde_json::Value>) {
        self.additional_data = value;
    }
    pub fn set_category(&mut self, value: Option<Category>) {
        self.category = value;
    }
    pub fn set_id(&mut self, value: Option<i64>) {
        self.id = value;
    }
    pub fn set_name(&mut self, value: Option<String>) {
        self.name = value;
    }
    pub fn set_photo_urls(&mut self, value: Vec<String>) {
        self.photo_urls = value;
    }
    pub fn set_status(&mut self, value: Option<PetStatus>) {
        self.status = value;
    }
    pub fn set_tags(&mut self, value: Vec<Tag>) {
        self.tags = value;
    }
}
