// Code generated by Microsoft Kiota - DO NOT EDIT.

use std::collections::HashMap;
use kiota_abstractions::{KiotaError, Parsable, ParseNode, SerializationWriter};

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Tag {
    /// The id property
    pub id: Option<i64>,
    /// The name property
    pub name: Option<String>,
    pub additional_data: HashMap<String, serde_json::Value>,
}

impl Parsable for Tag {
    fn field_names(&self) -> Vec<&'static str> {
        vec!["id", "name"]
    }

    fn assign_field(&mut self, field: &str, node: &dyn ParseNode) -> Result<(), KiotaError> {
        match field {
            "id" => self.id = node.get_i64_value()?,
            "name" => self.name = node.get_string_value()?,
            _ => {}
        }
        Ok(())
    }

    fn serialize(&self, writer: &mut dyn SerializationWriter) -> Result<(), KiotaError> {
        if let Some(val) = self.id { writer.write_i64_value(Some("id"), val)?; }
        if let Some(ref val) = self.name { writer.write_string_value(Some("name"), val)?; }
        writer.write_additional_data(&self.additional_data)?;
        Ok(())
    }

    fn as_any(self: Box<Self>) -> Box<dyn std::any::Any> {
        self
    }
}

impl Tag {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn create_from_discriminator_value(_parse_node: &dyn ParseNode) -> Result<Self, KiotaError> {
        Ok(Self::default())
    }
    pub fn get_additional_data(&self) -> &HashMap<String, serde_json::Value> {
        &self.additional_data
    }
    pub fn get_id(&self) -> &Option<i64> {
        &self.id
    }
    pub fn get_name(&self) -> &Option<String> {
        &self.name
    }
    pub fn set_additional_data(&mut self, value: HashMap<String, serde_json::Value>) {
        self.additional_data = value;
    }
    pub fn set_id(&mut self, value: Option<i64>) {
        self.id = value;
    }
    pub fn set_name(&mut self, value: Option<String>) {
        self.name = value;
    }
}
