// Code generated by Microsoft Kiota - DO NOT EDIT.

use std::collections::HashMap;
use kiota_abstractions::{KiotaError, Parsable, ParseNode, SerializationWriter};

#[derive(Debug, Clone, Default, PartialEq)]
pub struct User {
    /// The email property
    pub email: Option<String>,
    /// The firstName property
    pub first_name: Option<String>,
    /// The id property
    pub id: Option<i64>,
    /// The lastName property
    pub last_name: Option<String>,
    /// The password property
    pub password: Option<String>,
    /// The phone property
    pub phone: Option<String>,
    /// The username property
    pub username: Option<String>,
    /// User Status
    pub user_status: Option<i32>,
    pub additional_data: HashMap<String, serde_json::Value>,
}

impl Parsable for User {
    fn field_names(&self) -> Vec<&'static str> {
        vec!["email", "firstName", "id", "lastName", "password", "phone", "username", "userStatus"]
    }

    fn assign_field(&mut self, field: &str, node: &dyn ParseNode) -> Result<(), KiotaError> {
        match field {
            "email" => self.email = node.get_string_value()?,
            "firstName" => self.first_name = node.get_string_value()?,
            "id" => self.id = node.get_i64_value()?,
            "lastName" => self.last_name = node.get_string_value()?,
            "password" => self.password = node.get_string_value()?,
            "phone" => self.phone = node.get_string_value()?,
            "username" => self.username = node.get_string_value()?,
            "userStatus" => self.user_status = node.get_i32_value()?,
            _ => {}
        }
        Ok(())
    }

    fn serialize(&self, writer: &mut dyn SerializationWriter) -> Result<(), KiotaError> {
        if let Some(ref val) = self.email { writer.write_string_value(Some("email"), val)?; }
        if let Some(ref val) = self.first_name { writer.write_string_value(Some("firstName"), val)?; }
        if let Some(val) = self.id { writer.write_i64_value(Some("id"), val)?; }
        if let Some(ref val) = self.last_name { writer.write_string_value(Some("lastName"), val)?; }
        if let Some(ref val) = self.password { writer.write_string_value(Some("password"), val)?; }
        if let Some(ref val) = self.phone { writer.write_string_value(Some("phone"), val)?; }
        if let Some(ref val) = self.username { writer.write_string_value(Some("username"), val)?; }
        if let Some(val) = self.user_status { writer.write_i32_value(Some("userStatus"), val)?; }
        writer.write_additional_data(&self.additional_data)?;
        Ok(())
    }

    fn as_any(self: Box<Self>) -> Box<dyn std::any::Any> {
        self
    }
}

impl User {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn create_from_discriminator_value(_parse_node: &dyn ParseNode) -> Result<Self, KiotaError> {
        Ok(Self::default())
    }
    pub fn get_additional_data(&self) -> &HashMap<String, serde_json::Value> {
        &self.additional_data
    }
    pub fn get_email(&self) -> &Option<String> {
        &self.email
    }
    pub fn get_first_name(&self) -> &Option<String> {
        &self.first_name
    }
    pub fn get_id(&self) -> &Option<i64> {
        &self.id
    }
    pub fn get_last_name(&self) -> &Option<String> {
        &self.last_name
    }
    pub fn get_password(&self) -> &Option<String> {
        &self.password
    }
    pub fn get_phone(&self) -> &Option<String> {
        &self.phone
    }
    pub fn get_user_status(&self) -> &Option<i32> {
        &self.user_status
    }
    pub fn get_username(&self) -> &Option<String> {
        &self.username
    }
    pub fn set_additional_data(&mut self, value: HashMap<String, serde_json::Value>) {
        self.additional_data = value;
    }
    pub fn set_email(&mut self, value: Option<String>) {
        self.email = value;
    }
    pub fn set_first_name(&mut self, value: Option<String>) {
        self.first_name = value;
    }
    pub fn set_id(&mut self, value: Option<i64>) {
        self.id = value;
    }
    pub fn set_last_name(&mut self, value: Option<String>) {
        self.last_name = value;
    }
    pub fn set_password(&mut self, value: Option<String>) {
        self.password = value;
    }
    pub fn set_phone(&mut self, value: Option<String>) {
        self.phone = value;
    }
    pub fn set_user_status(&mut self, value: Option<i32>) {
        self.user_status = value;
    }
    pub fn set_username(&mut self, value: Option<String>) {
        self.username = value;
    }
}
