// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, DefaultQueryParameters, HttpMethod, KiotaError, Parsable, ParseNode, RequestAdapter, RequestConfiguration, RequestInformation};
use crate::models::pet::Pet;

/// Builds and executes requests for operations under \pet\findByStatus
#[derive(Debug, Clone, Default, PartialEq)]
pub struct FindByStatusRequestBuilder {
    pub base: BaseRequestBuilder,
}

impl FindByStatusRequestBuilder {
    pub fn new(path_parameters: std::collections::HashMap<String, String>, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}/pet/findByStatus?status={status}".to_string(), path_parameters),
        }
    }
    pub fn with_url(raw_url: &str, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        path_parameters.insert("request-raw-url".to_string(), raw_url.to_string());
        Self {
            base: BaseRequestBuilder::new(request_adapter, String::new(), path_parameters),
        }
    }
    /// Multiple status values can be provided with comma separated strings
    pub async fn get(&self, config: Option<&RequestConfiguration<FindByStatusRequestBuilderGetQueryParameters>>) -> Result<Vec<Pet>, KiotaError> {
        let request_info = self.to_get_request_information(config)?;
        let factory: Box<dyn Fn(&dyn ParseNode) -> Result<Box<dyn Parsable>, KiotaError> + Send + Sync> =
            Box::new(|node| Ok(Box::new(Pet::create_from_discriminator_value(node)?)));
        let results = self.base.request_adapter.send_collection(&request_info, &factory, None).await?;
        let typed: Vec<Pet> = results.into_iter().filter_map(|r| {
            r.as_any().downcast::<Pet>().ok().map(|b| *b)
        }).collect();
        Ok(typed)
    }
    /// Multiple status values can be provided with comma separated strings
    pub fn to_get_request_information(&self, config: Option<&RequestConfiguration<FindByStatusRequestBuilderGetQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Get, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        Ok(request_info)
    }
}

#[derive(Debug, Clone, Default)]
pub struct FindByStatusRequestBuilderGetQueryParameters {
    /// Status values that need to be considered for filter
    pub status: Vec<String>,
}

impl kiota_abstractions::QueryParameters for FindByStatusRequestBuilderGetQueryParameters {
    fn to_query_parameters(&self) -> std::collections::HashMap<String, String> {
        let mut params = std::collections::HashMap::new();
        if !self.status.is_empty() { params.insert("status".to_string(), self.status.join(",")); }
        params
    }
}
