// Code generated by Microsoft Kiota - DO NOT EDIT.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GetStatusQueryParameterType {
    Available,
    Pending,
    Sold,
}

impl std::fmt::Display for GetStatusQueryParameterType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Available => write!(f, "available"),
            Self::Pending => write!(f, "pending"),
            Self::Sold => write!(f, "sold"),
        }
    }
}

impl GetStatusQueryParameterType {
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "available" => Some(Self::Available),
            "pending" => Some(Self::Pending),
            "sold" => Some(Self::Sold),
            _ => None,
        }
    }
}
