// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, DefaultQueryParameters, HttpMethod, KiotaError, Parsable, ParseNode, RequestAdapter, RequestConfiguration, RequestInformation};
use crate::models::user::User;

/// Builds and executes requests for operations under \user\{username}
#[derive(Debug, Clone, Default, PartialEq)]
pub struct WithUsernameItemRequestBuilder {
    pub base: BaseRequestBuilder,
}

impl WithUsernameItemRequestBuilder {
    pub fn new(path_parameters: std::collections::HashMap<String, String>, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}/user/{username}".to_string(), path_parameters),
        }
    }
    pub fn with_url(raw_url: &str, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        path_parameters.insert("request-raw-url".to_string(), raw_url.to_string());
        Self {
            base: BaseRequestBuilder::new(request_adapter, String::new(), path_parameters),
        }
    }
    /// This can only be done by the logged in user.
    pub async fn delete(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<Option<Vec<u8>>, KiotaError> {
        let request_info = self.to_delete_request_information(config)?;
        self.base.request_adapter.send_primitive(&request_info, None).await
    }
    /// Get user by user name
    pub async fn get(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<Option<User>, KiotaError> {
        let request_info = self.to_get_request_information(config)?;
        let factory: Box<dyn Fn(&dyn ParseNode) -> Result<Box<dyn Parsable>, KiotaError> + Send + Sync> =
            Box::new(|node| Ok(Box::new(User::create_from_discriminator_value(node)?)));
        let result = self.base.request_adapter.send(&request_info, &factory, None).await?;
        Ok(result.and_then(|r| r.as_any().downcast::<User>().ok().map(|b| *b)))
    }
    /// This can only be done by the logged in user.
    pub async fn put(&self, body: &Option<User>, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<Option<Vec<u8>>, KiotaError> {
        let request_info = self.to_put_request_information(body, config)?;
        self.base.request_adapter.send_primitive(&request_info, None).await
    }
    /// This can only be done by the logged in user.
    pub fn to_delete_request_information(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Delete, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        Ok(request_info)
    }
    pub fn to_get_request_information(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Get, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        Ok(request_info)
    }
    /// This can only be done by the logged in user.
    pub fn to_put_request_information(&self, body: &Option<User>, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Put, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        if let Some(ref b) = body {
            request_info.set_content_from_parsable(self.base.request_adapter.serialization_writer_factory(), "application/json", b as &dyn Parsable)?;
        }
        Ok(request_info)
    }
}
