// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, DefaultQueryParameters, HttpMethod, KiotaError, Parsable, ParseNode, RequestAdapter, RequestConfiguration, RequestInformation};
use crate::models::pet::Pet;
use crate::pet::find_by_status::find_by_status_request_builder::FindByStatusRequestBuilder;
use crate::pet::find_by_tags::find_by_tags_request_builder::FindByTagsRequestBuilder;
use crate::pet::item::with_pet_item_request_builder::WithPetItemRequestBuilder;

/// Builds and executes requests for operations under \pet
#[derive(Debug, Clone, Default, PartialEq)]
pub struct PetRequestBuilder {
    pub base: BaseRequestBuilder,
}

impl PetRequestBuilder {
    /// The findByStatus property
    pub fn find_by_status(&self) -> FindByStatusRequestBuilder {
        FindByStatusRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    /// The findByTags property
    pub fn find_by_tags(&self) -> FindByTagsRequestBuilder {
        FindByTagsRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    /// Gets an item from the petstore_client.pet.item collection
    pub fn by_pet_id(&self, pet_id: i64) -> WithPetItemRequestBuilder {
        let mut url_tpl_params = self.base.path_parameters.clone();
        url_tpl_params.insert("petId".to_string(), pet_id.to_string());
        WithPetItemRequestBuilder::new(url_tpl_params, self.base.request_adapter.clone())
    }
    pub fn new(path_parameters: std::collections::HashMap<String, String>, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}/pet".to_string(), path_parameters),
        }
    }
    pub fn with_url(raw_url: &str, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        path_parameters.insert("request-raw-url".to_string(), raw_url.to_string());
        Self {
            base: BaseRequestBuilder::new(request_adapter, String::new(), path_parameters),
        }
    }
    /// Add a new pet to the store
    pub async fn post(&self, body: &Option<Pet>, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<Option<Vec<u8>>, KiotaError> {
        let request_info = self.to_post_request_information(body, config)?;
        self.base.request_adapter.send_primitive(&request_info, None).await
    }
    /// Update an existing pet
    pub async fn put(&self, body: &Option<Pet>, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<Option<Vec<u8>>, KiotaError> {
        let request_info = self.to_put_request_information(body, config)?;
        self.base.request_adapter.send_primitive(&request_info, None).await
    }
    pub fn to_post_request_information(&self, body: &Option<Pet>, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Post, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        if let Some(ref b) = body {
            request_info.set_content_from_parsable(self.base.request_adapter.serialization_writer_factory(), "application/json", b as &dyn Parsable)?;
        }
        Ok(request_info)
    }
    pub fn to_put_request_information(&self, body: &Option<Pet>, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Put, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        if let Some(ref b) = body {
            request_info.set_content_from_parsable(self.base.request_adapter.serialization_writer_factory(), "application/json", b as &dyn Parsable)?;
        }
        Ok(request_info)
    }
}
