// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, RequestAdapter};
use crate::repos::item::with_owner_item_request_builder::WithOwnerItemRequestBuilder;

/// Builds and executes requests for operations under \repos
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ReposRequestBuilder {
    pub base: BaseRequestBuilder,
}

impl ReposRequestBuilder {
    /// Gets an item from the github_releases_client.repos.item collection
    pub fn by_owner(&self, owner: String) -> WithOwnerItemRequestBuilder {
        let mut url_tpl_params = self.base.path_parameters.clone();
        url_tpl_params.insert("owner".to_string(), owner.to_string());
        WithOwnerItemRequestBuilder::new(url_tpl_params, self.base.request_adapter.clone())
    }
    pub fn new(path_parameters: std::collections::HashMap<String, String>, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}/repos".to_string(), path_parameters),
        }
    }
    pub fn with_url(raw_url: &str, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        path_parameters.insert("request-raw-url".to_string(), raw_url.to_string());
        Self {
            base: BaseRequestBuilder::new(request_adapter, String::new(), path_parameters),
        }
    }
}
