// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, DefaultQueryParameters, HttpMethod, KiotaError, Parsable, ParseNode, RequestAdapter, RequestConfiguration, RequestInformation};
use crate::store::inventory::inventory_get_response::InventoryGetResponse;

/// Builds and executes requests for operations under \store\inventory
#[derive(Debug, Clone, Default, PartialEq)]
pub struct InventoryRequestBuilder {
    pub base: BaseRequestBuilder,
}

impl InventoryRequestBuilder {
    pub fn new(path_parameters: std::collections::HashMap<String, String>, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}/store/inventory".to_string(), path_parameters),
        }
    }
    pub fn with_url(raw_url: &str, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        path_parameters.insert("request-raw-url".to_string(), raw_url.to_string());
        Self {
            base: BaseRequestBuilder::new(request_adapter, String::new(), path_parameters),
        }
    }
    /// Returns a map of status codes to quantities
    pub async fn get(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<Option<InventoryGetResponse>, KiotaError> {
        let request_info = self.to_get_request_information(config)?;
        let factory: Box<dyn Fn(&dyn ParseNode) -> Result<Box<dyn Parsable>, KiotaError> + Send + Sync> =
            Box::new(|node| Ok(Box::new(InventoryGetResponse::create_from_discriminator_value(node)?)));
        let result = self.base.request_adapter.send(&request_info, &factory, None).await?;
        Ok(result.and_then(|r| r.as_any().downcast::<InventoryGetResponse>().ok().map(|b| *b)))
    }
    /// Returns a map of status codes to quantities
    pub fn to_get_request_information(&self, config: Option<&RequestConfiguration<DefaultQueryParameters>>) -> Result<RequestInformation, KiotaError> {
        let mut request_info = RequestInformation::new_with_method_and_url_template(HttpMethod::Get, &self.base.url_template, self.base.path_parameters.clone());
        if let Some(c) = config {
            request_info.configure(c);
        }
        request_info.headers.try_add("Accept", "application/json");
        Ok(request_info)
    }
}
