// Code generated by Microsoft Kiota - DO NOT EDIT.

use kiota_abstractions::{BaseRequestBuilder, RequestAdapter};
use crate::repos::item::item::releases::releases_request_builder::ReleasesRequestBuilder;

/// Builds and executes requests for operations under \repos\{owner}\{repo}
#[derive(Debug, Clone, Default, PartialEq)]
pub struct WithRepoItemRequestBuilder {
    pub base: BaseRequestBuilder,
}

impl WithRepoItemRequestBuilder {
    /// The releases property
    pub fn releases(&self) -> ReleasesRequestBuilder {
        ReleasesRequestBuilder::new(self.base.path_parameters.clone(), self.base.request_adapter.clone())
    }
    pub fn new(path_parameters: std::collections::HashMap<String, String>, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        Self {
            base: BaseRequestBuilder::new(request_adapter, "{+baseurl}/repos/{owner}/{repo}".to_string(), path_parameters),
        }
    }
    pub fn with_url(raw_url: &str, request_adapter: std::sync::Arc<dyn RequestAdapter>) -> Self {
        let mut path_parameters = std::collections::HashMap::new();
        path_parameters.insert("request-raw-url".to_string(), raw_url.to_string());
        Self {
            base: BaseRequestBuilder::new(request_adapter, String::new(), path_parameters),
        }
    }
}
